### ISSUE TITLE
Env variable KEYCLOAK_ADMIN_USER does not exist

### ISSUE THREAD

**Issue by git-pesche** [JMarkstrom/SafeNet-Keycloak-Agent#1]
Hi 

Thanks a lot for providing your guide for running Keycloak with certs!

When I tried it, I stumppled with the 1st admin login. Then I recognized, that the env variable KEYCLOAK_ADMIN_USER  was wrong. With  just KEYCLOAK_ADMIN it worked.

see also KC docu: https://www.keycloak.org/server/configuration#_creating_the_initial_admin_user

https://github.com/JMarkstrom/Keycloak/blame/16cc6e4cbb8b3913909f5bff127c0e319489a453/files/keycloak.yml#L19

**Comment by JMarkstrom** [comment]
Thank you, I have updated the file in question. Will revisit documentation as needed.
